/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "onnx.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(onnx_AttributeProto, onnx_AttributeProto, 2)


PB_BIND(onnx_ValueInfoProto, onnx_ValueInfoProto, 2)


PB_BIND(onnx_NodeProto, onnx_NodeProto, 2)


PB_BIND(onnx_IntIntListEntryProto, onnx_IntIntListEntryProto, AUTO)


PB_BIND(onnx_NodeDeviceConfigurationProto, onnx_NodeDeviceConfigurationProto, AUTO)


PB_BIND(onnx_ShardingSpecProto, onnx_ShardingSpecProto, AUTO)


PB_BIND(onnx_ShardedDimProto, onnx_ShardedDimProto, AUTO)


PB_BIND(onnx_SimpleShardedDimProto, onnx_SimpleShardedDimProto, AUTO)


PB_BIND(onnx_TrainingInfoProto, onnx_TrainingInfoProto, 2)


PB_BIND(onnx_ModelProto, onnx_ModelProto, 2)


PB_BIND(onnx_DeviceConfigurationProto, onnx_DeviceConfigurationProto, AUTO)


PB_BIND(onnx_StringStringEntryProto, onnx_StringStringEntryProto, 2)


PB_BIND(onnx_TensorAnnotation, onnx_TensorAnnotation, AUTO)


PB_BIND(onnx_GraphProto, onnx_GraphProto, 2)


PB_BIND(onnx_TensorProto, onnx_TensorProto, 2)


PB_BIND(onnx_TensorProto_Segment, onnx_TensorProto_Segment, AUTO)


PB_BIND(onnx_SparseTensorProto, onnx_SparseTensorProto, 2)


PB_BIND(onnx_TensorShapeProto, onnx_TensorShapeProto, 2)


PB_BIND(onnx_TensorShapeProto_Dimension, onnx_TensorShapeProto_Dimension, AUTO)


PB_BIND(onnx_TypeProto, onnx_TypeProto, 2)


PB_BIND(onnx_TypeProto_Tensor, onnx_TypeProto_Tensor, 2)


PB_BIND(onnx_TypeProto_Sequence, onnx_TypeProto_Sequence, AUTO)


PB_BIND(onnx_TypeProto_Map, onnx_TypeProto_Map, AUTO)


PB_BIND(onnx_TypeProto_Optional, onnx_TypeProto_Optional, AUTO)


PB_BIND(onnx_TypeProto_SparseTensor, onnx_TypeProto_SparseTensor, 2)


PB_BIND(onnx_OperatorSetIdProto, onnx_OperatorSetIdProto, 2)


PB_BIND(onnx_FunctionProto, onnx_FunctionProto, 2)













#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

